// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GrpcService1 {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgRlbnVtKkgKDEFCSUxJVFlfVFlQRRIdChlBQklMSVRZ",
            "X1NUQVJUX01PTkVZX0JPTlVTEAASGQoMQUJJTElUWV9OT05FEP//////////",
            "/wFCD6oCDEdycGNTZXJ2aWNlMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GrpcService1.ABILITY_TYPE), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ABILITY_TYPE {
    [pbr::OriginalName("ABILITY_START_MONEY_BONUS")] AbilityStartMoneyBonus = 0,
    [pbr::OriginalName("ABILITY_NONE")] AbilityNone = -1,
  }

  #endregion

}

#endregion Designer generated code
